language: java
jdk:
  - openjdk8
install: true
cache:
  directories:
    - $HOME/.m2
before_install:
  - chmod +x mvnw
before_script:
  - git config user.name "$COMMIT_AUTHOR_NAME"
  - git config user.email "$COMMIT_AUTHOR_EMAIL"
  - export COMMIT_MESSAGE=`git log -1 --oneline`

script:
  - echo $COMMIT_MESSAGE
  - jdk_switcher use openjdk8
  - ./mvnw clean install